#+TITLE: README for Vagrant dev linux box
#+AUTHOR:   Roman Shestakov
#+LANGUAGE: en

* Description

Ansible based configuration used to setup development hosts. This
Vcoub be used with Ubuntu, Centos7 and AWS linux2022.  Ansible roles
are used to build gcc, llvm and some other packages from sources.

* how to use
** Install Ansible
#+BEGIN_SRC
# linux  
$ sudo apt-get install ansible
#+END_SRC

#+BEGIN_SRC
# mac
$ brew install ansible
#+END_SRC


** Run make
this will run ansible book to update locate host
#+BEGIN_SRC
$ make run_localhost
#+END_SRC

** Run run_vagrant_docker

in case is docker has troubles connecting - 
make sure to update vagrant. It installs private ssh key to ~/.vagrant.d and then uses it
during docker container provision. The usecure public key is inserted into Docker container
Vagrant account is added with NOPASSWD sudo access

Runs Vangrant to provision a docker container
this is usefull becuase we can test provision inside a new docker container without impacting local host 
#+BEGIN_SRC
$ make run_vagrant_docker
# to connect to docker vm  
sudo vagrant ssh
#+END_SRC


check Makefile for different targets

* How the project is structured
** src/playbooks - contains ansible playbook
** config - used for different ansible.cfg files used for different cases.
in Makefile while executing a specific host target ANSIBLE_CONFIG=./config/local/ansible.cfg is set to point to a required config
** inventory - different inventory files, in Makefile specified by -i ./inventory/local_inventory.txt
** bin/role_update.sh - is used to pull ansible roles which are used during host provision. The roles are put into src/playbooks/roles/external
this location is specified in ansible.cfg files like:
roles_path=../../src/playbooks/roles/internal:../../src/playbooks/roles/external 
so the playbook could find the roles
