#+TITLE: README for Vagrant dev linux box
#+AUTHOR:   Roman Shestakov
#+LANGUAGE: en

* Description

Ansible based configuration used to setup development hosts. This
Vcoub be used with Ubuntu, Centos7 and AWS linux2022.  Ansible roles
are used to build gcc, llvm and some other packages from sources.

* how to use
** Install Ansible
#+BEGIN_SRC
$ brew install ansible
#+END_SRC

** Run make
#+BEGIN_SRC
$ make run_localhost
#+END_SRC

check Makefile for different targets

* How the project is structured
** src/playbooks - contains ansible playbook
** config - used for different ansible.cfg files used for different cases.
in Makefile while executing a specific host target ANSIBLE_CONFIG=./config/local/ansible.cfg is set to point to a required config
** inventory - different inventory files, in Makefile specified by -i ./inventory/local_inventory.txt
** bin/role_update.sh - is used to pull ansible roles which are used during host provision. The roles are put into src/playbooks/roles/external
this location is specified in ansible.cfg files like:
roles_path=../../src/playbooks/roles/internal:../../src/playbooks/roles/external 
so the playbook could find the roles
