# meta/main.yml

galaxy_info:
  author: Roman Shestakov
  description: Install emacs
  min_ansible_version: 1.4
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - system

dependencies:
  # - {role: ANXS.build-essential, tags: build-essential }
  # - {role: geerlingguy.git, tags: git }
