# file: ansible-role-flatbuffers/meta/main.yml

galaxy_info:
  author:
  company:
  description: Install GTest
  min_ansible_version: 0.1
  license: MIT
  platforms:
  - name: Centos
    versions:
    - all
  categories:
  - system
