# vm.yml - play to install a VM

- name: vm.yml
  hosts: all
  # connection: paramiko
  # vars:
  #   ansible_ssh_private_key_file: /path/to/private_key
  #   ansible_ssh_pass: passphrase_for_private_key

  # https://stackoverflow.com/questions/35616021/ansible-sudo-hangs-after-5-tasks
  pre_tasks:
    - name: Disable Fingerprint checking that may be enabled.  When enabled, causes SSH issues.
      command: authconfig --disablefingerprint --update

  roles:
    - { role: RomanShestakov.ansible-role-dotfiles, dotfiles_repo_url: "https://github.com/RomanShestakov/dotfiles.git", dotfiles_dest: "/home/vagrant" }
    - { role: RomanShestakov.ansible-role-tmux, become: yes, tags: ["tmux"] }
    - { role: RomanShestakov.ansible-role-emacs, become: yes, emacs_version: "emacs-27.1", tags: ["emacs"] }
    - { role: RomanShestakov.ansible-role-valgrind, become: yes, tags: ["valgrind"] }
    - { role: RomanShestakov.ansible-role-protobuf, gcc_version: 8.2.0, become: yes, tags: ["protobuf"] }
    - { role: RomanShestakov.ansible-role-antrl, tags: ["antrl"] }
    # - { role: geerlingguy.java, become: yes, tags: ["java"] }
    # - { role: RomanShestakov.ansible-role-common-tools, become: yes, tags: ["build-common"] }
    - role: geerlingguy.java
      become: yes
      # when: "ansible_of_family == 'RedHat'"
      java_home: "/opt/java"
      java_packages:
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-devel

  post_tasks:
    - name: .EMACS | get .emacs git repository
      become: yes
      become_user: vagrant
      git: repo="https://github.com/RomanShestakov/.emacs.d.git" dest="/home/vagrant/.emacs.d" accept_hostkey=yes force=yes

    - name: Create a directory to write mem dumps, if it does not exist
      file:
        path: /tmp/cores
        state: directory
        mode: '0777'

    - name: Set kernel.core_pattern in sysctl
      become: yes
      sysctl:
        name: kernel.core_pattern
        value: "/tmp/cores/core.%e.%p.%h.%"
        state: present
        reload: yes
