---

# file: tasks/deps.yml

- name: Tools for emacs build Ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:

  - build-essential
  - texinfo
  - libgnutls28-dev
  - libjpeg-dev
  - libpng-dev
  - libtiff5-dev
  - libgif-dev
  - libxpm-dev
  - libncurses-dev
  - libgtk-3-dev
  # install tree-sitter
  - libtree-sitter-dev
  - libmagick++-dev
  - gcc-13
  - g++-13
  - libgccjit0
  - libgccjit-13-dev
  - clang
  - clangd
  # bear is used to generate compilation database
  - bear
  - autoconf
  - libjansson4
  - libjansson-dev

  #when: ansible_distribution == "Ubuntu"

...
