# meta/main.yml

galaxy_info:
  author: Roman Shestakov
  description: Install dotfiles
  min_ansible_version: 1.4
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - system

# dependencies:
#   - {role: geerlingguy.git, tags: git }
